### ISSUE TITLE
hxt is instantiated twice

### ISSUE THREAD

**Issue by jcward** [MintPaw/hxScoutTest#1]
Hi @MintPaw,

So because HaxeFlixel is OpenFL-based, my OpenFL already instantiates hxt. Your instantiation in Main.hx created cross-talk and crashed (I need to throw on two hxtelemetry instances from the same thread.)

For OpenFL-based apps, you configure hxtelemetry like this, just drop this function in your `Main.hx`:

```
public static var telemetry_config:Bool = (function():Bool {
#if (cpp && telemetry)
    openfl.Telemetry.config.app_name = "HaxeFlixel";
    //openfl.Telemetry.config.allocations = false;
#if android
    openfl.Telemetry.config.host = "10.0.1.33";
#end
#end
  return true;
})();
```

**Comment by MintPaw** [comment]
Oh, so I only need to make an instance of hxt if I'm not using openfl. Got it.
